name: Pull requests

on:
  pull_request:
    branches:
    - "**"

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    # - name: Set up Go 1.x
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: ^1.15
    #   id: go

    - uses: actions/checkout@v2

    - name: Run tests in docker
      run: make docker-test
