name: Pull requests

on:
  pull_request:
    branches:
    - "**"

env:
  PROJECT: go-example

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run test
      run: make test
